using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Override
{


    public class PortfolioContext : DbContext
    {
        public PortfolioContext(DbContextOptions<PortfolioContext> options) : base(options) { }

        public DbSet<Portfolio> PortfolioOverride { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Optionally configure the entity further if needed
            modelBuilder.Entity<Portfolio>()
                .Property(p => p.Id)
                .ValueGeneratedOnAdd();  // This specifies that the Id value is generated by the database
        }
    }
}
